language: node_js
node_js:
  - "12"
addons:
    code_climate:
        repo_token: d4c82676da0d74af43925c9d7833de711d996a11931c1c8c35eb0797da457b93 
before_script:
after_script:
  - codeclimate-test-reporter < lcov.info
