version: '3.8'

services:
  postgis:
    image: postgis/postgis
    container_name: postgis
    volumes:
      - ./test/data/sql-scripts:/sql-scripts
    command:
      [
        "bash",
        "-c",
        "psql -U postgres -d flooddev -f /sql-scripts/u_flood.sql && psql -U postgres -d flooddev -f /sql-scripts/views.sql && psql -U postgres -d flooddev -f /sql-scripts/data.sql && psql -U postgres -d flooddev -f /sql-scripts/u_flood-insert.sql"
      ]
    networks:
      - postgresnet
    environment:
      POSTGRES_PASSWORD: fr24Password
      POSTGRES_DB: flooddev
    ports:
      - 5432:5432

  # pgadmin4:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin4
  #   networks:
  #     - postgresnet
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@gmail.com
  #     PGADMIN_DEFAULT_PASSWORD: pgadmin_password
  #   ports:
  #     - 8080:80

  s3-ninja:
    image: scireum/s3-ninja
    container_name: s3-ninja
    ports:
      - '9444:9000'
    volumes:
      - s3ninja-data:/home/sirius/data
    user: '2000:2000'

networks:
  postgresnet:
    driver: bridge
volumes:
  s3ninja-data:
    driver: local
