services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    env_file:
      - ./docker/.env
    environment:
      - SERVICES=lambda,s3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
