version: '3.8'
services:
  s3-ninja:
    image: scireum/s3-ninja
    container_name: s3-ninja
    ports:
      - '9444:9000'
    volumes:
      - s3ninja-data:/home/sirius/data
    user: '2000:2000'
volumes:
  postgres:
  s3ninja-data:
    driver: local

    # https://s3ninja.net/
