module.exports = {
  DOCKER_AWS_ACCESS_KEY_ID: 'AKIAIOSFODNN7EXAMPLE',
  DOCKER_AWS_SECRET_ACCESS_KEY: 'wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY',
  DOCKER_AWS_ENDPOINT: 'http://localhost:9444',
  DOCKER_AWS_FORCE_STYLE: true
}
