name: CI

on: [push, pull_request]
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
              with:
                fetch-depth: 0

            - name: Install nodejs
              uses: actions/setup-node@v1
              with:
                node-version: "16.x"
            
            - name: Install node dependencies
              run: npm ci

            - name: Run linting
              run: npm run lint

            - name: Run unit tests
              run: |
                npm run unit-test
                sed -i 's/\/home\/runner\/work\/flood-data\/flood-data\//\/github\/workspace\//g' coverage/lcov.info

            - name: Start containers
              run: |
                docker-compose -f "docker-compose.yml" up -d --build -T
              working-directory: .

            - name: see dir list
              run: cd ./test
              working-directory: .

            - name: migrate:tests
              run: npm run migrate:tests
              working-directory: .

            - name: Stop containers
              if: always()
              run: docker-compose -f "docker-compose.yml" down -T
              working-directory: .

            - name: Analyse code quality
              uses: sonarsource/sonarcloud-github-action@master
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              with:
                args: >
                  -Dsonar.organization=defra
                  -Dsonar.projectKey=DEFRA_flood-data
                  -Dsonar.exclusions=**/node_modules/**,**/test/**,**/test-output/**,**/queries.js
                  -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
                  -Dsonar.javascript.exclusions=**/node_modules/**,**/test/**,**/test-output/**,**/queries.js
